name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }} / ${{ matrix.target }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            setup: sudo apt-get install musl-tools

          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
            setup: sudo apt-get install musl-tools

          - os: windows-2022
            target: x86_64-pc-windows-msvc
            setup: git config --global core.longpaths true

          - os: macos-13
            target: x86_64-apple-darwin
            setup: ""

          - os: macos-14
            target: aarch64-apple-darwin
            setup: ""

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install dependencies
        if: matrix.setup != ''
        run: ${{ matrix.setup }}

      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build archive
        shell: bash
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"

          if [ "${{ matrix.os }}" = "windows-2019" ]; then
            ARCHIVE="sgleam-$VERSION-${{ matrix.target }}.zip"
            cp "target/${{ matrix.target }}/release/sgleam.exe" "sgleam.exe"
            7z a "$ARCHIVE" "sgleam.exe"
            rm sgleam.exe
          else
            ARCHIVE="sgleam-$VERSION-${{ matrix.target }}.tar.gz"
            cp "target/${{ matrix.target }}/release/sgleam" "sgleam"
            tar -czvf "$ARCHIVE" "sgleam"
            rm sgleam
          fi

          openssl dgst -r -sha256 -out "$ARCHIVE".sha256 "$ARCHIVE"
          echo "ASSET=$ARCHIVE" >> $GITHUB_ENV

      - name: Ensure binary successfully boots
        shell: bash
        run: |
          case "${{ matrix.target }}" in
            x86_64-pc-windows-msvc)
              7z x "$ASSET"
              ./sgleam.exe --version ;;
            *)
              tar -xvzf "$ASSET"
              ./sgleam --version ;;
          esac

      - name: Upload release archive
        # https://github.com/softprops/action-gh-release/issues/445
        # uses: softprops/action-gh-release@v2
        uses: softprops/action-gh-release@0bd7e8b279c9b5b36661d552472fbbfe671fe26e
        with:
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            ${{ env.ASSET }}
            ${{ env.ASSET }}.sha256
